site_name: trace-dkey
theme:
  name: material
  palette:
    primary: teal
    accent: deep orange
nav:
  - Home: index.md
  - Usage: usage.md
repo_url: https://github.com/Agent-Hellboy/trace-dkey
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


